version: '3'
services:
  docker-api:
    restart: always
    build:
      context: .
      dockerfile: MultiStage.Dockerfile
    expose:
      - '3000'
    environment:
      PING_LISTEN_PORT: 3000
    deploy:
      replicas: 4
    networks:
      - front-network
    volumes:
      - .:/app

  proxy:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    networks:
      - front-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - docker-api

networks:
  front-network:
    driver: bridge